히든레이어

보스턴집값예측 :  https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

아이리스 품종 분류 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

보스턴집값예측

In [2]:
#1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

#독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [4]:
#2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [6]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [5]:
#3. 데이터로 모델을 학습 합니다.
model.fit(독립, 종속, epochs=10000,verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 13.7112
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 12.9293
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 13.1195
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 13.1494
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2705
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2868
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 12.9762
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 13.0562
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 12.8017
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 12.8628


In [7]:
#4. 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[31.496399]
 [21.473011]
 [31.223465]
 [36.966923]
 [34.39058 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


아이리스 품종 분류


In [8]:
#1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

#원핫인코딩
인코딩 = pd.get_dummies(아이리스)

#독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [10]:
#2.모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,  Y)
model.compile(loss ='categorical_crossentropy', metrics='accuracy')

In [ ]:
#3.데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs=100)

In [13]:
#4.모델을 이용합니다.
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.8559338e-01 1.3504264e-02 9.0235966e-04]
 [9.5722556e-01 4.0303841e-02 2.4706542e-03]
 [9.7824472e-01 2.0361273e-02 1.3940637e-03]
 [9.6008211e-01 3.7543967e-02 2.3739166e-03]
 [9.8868096e-01 1.0571522e-02 7.4749033e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
